// The Outfitter Pi extension body: startup branding, plan/build mode, and /outfitter onboarding.
import type { ContextEvent, ExtensionAPI } from '@earendil-works/pi-coding-agent';

import { matchesKey } from './piTui.js';

import type { OutfitterExtensionConfig } from './config.js';
import { selectDescribedOption } from './describedSelect.js';
import { createStartupHeaderLines } from './header.js';
import {
  createOutfitterPaths,
  runCreateProfileOnboarding,
  runDefaultCatalogOnboarding,
  runProvidedSourceOnboarding,
  runRemoteSettingsOnboarding,
} from './onboardingFlows.js';
import { formatProfileLabel } from './profileDiscovery.js';
import type { InstallTarget, OnboardingFs, OutfitterContext, QuestionUi } from './types.js';
import { loadPrivateCatalogOnboarding } from './types.js';

const OUTFITTER_PLAN_TOOLS = ['read', 'grep', 'find', 'ls'];
const OUTFITTER_DEFAULT_TOOLS = ['read', 'bash', 'edit', 'write'];

// pi-coding-agent does not re-export pi-agent-core's AgentMessage; derive it from
// the context event so the shape still tracks pi's published types.
type AgentMessage = ContextEvent['messages'][number];

// pi's published extension types do not declare the `project_trust` event yet even
// though the runtime emits it; keep this local registration shape until they do.
interface ProjectTrustEvent {
  readonly cwd?: string;
}

interface ProjectTrustResult {
  readonly trusted: 'yes' | 'undecided';
  readonly remember?: boolean;
}

type ProjectTrustRegistrar = (
  event: 'project_trust',
  handler: (event: ProjectTrustEvent) => Promise<ProjectTrustResult>,
) => void;

const isOutfitterModeContextMessage = (message: AgentMessage): boolean =>
  'customType' in message && message.customType === 'outfitter-mode-context';

// Duck-typed lookups keep the runtime guards for hosts older than the declared pi API
// without tripping unbound-method lint on pi's method-typed declarations.
const hasContextFunction = (host: object, name: string): boolean =>
  typeof (host as Readonly<Record<string, unknown>>)[name] === 'function';

const exportRuntimeSystemPrompt = async (ctx: OutfitterContext): Promise<void> => {
  /* v8 ignore next -- `typeof process` guards non-node extension hosts; tests always run under node. */
  const outputPath = typeof process === 'undefined' ? undefined : process.env.OUTFITTER_SYSTEM_PROMPT_EXPORT_PATH;
  if (!outputPath || !hasContextFunction(ctx, 'getSystemPrompt')) return;

  const systemPrompt: unknown = ctx.getSystemPrompt();
  if (typeof systemPrompt !== 'string') return;

  const [fsModule, pathModule] = await Promise.all([import('node:fs'), import('node:path')]);
  fsModule.mkdirSync(pathModule.dirname(outputPath), { recursive: true });
  fsModule.writeFileSync(
    outputPath,
    [
      '<!-- Generated by Outfitter from Pi runtime ctx.getSystemPrompt(). Safe to review or git-ignore. Do not edit by hand. -->',
      '# Generated Pi runtime system prompt',
      '',
      systemPrompt,
      '',
    ].join('\n'),
  );
};

const submitSlashCommand = async (ctx: OutfitterContext, command: string): Promise<boolean> => {
  /* v8 ignore next 2 -- every caller already guards on the TUI mode; kept as a safety net for new call sites. */
  if (ctx.mode !== 'tui') return false;

  ctx.ui.setEditorText(command);
  await ctx.ui.custom<boolean>(
    (tui, _theme, _keybindings, done) => {
      setTimeout(() => {
        // `focusedComponent` is private on pi's TUI class but submitting the prepared
        // editor text through the focused editor is the only stable submission path.
        const focusHost = tui as unknown as { focusedComponent?: { handleInput?: (data: string) => void } };
        focusHost.focusedComponent?.handleInput?.('\r');
        done(true);
      }, 25);

      return {
        render: () => [],
        invalidate: () => undefined,
      };
    },
    { overlay: true, overlayOptions: { nonCapturing: true, visible: () => false } },
  );
  return true;
};

const getAvailableModelCount = async (ctx: OutfitterContext): Promise<number> => {
  const modelRegistry = ctx.modelRegistry as OutfitterContext['modelRegistry'] | undefined;
  if (modelRegistry === undefined || !hasContextFunction(modelRegistry, 'getAvailable')) {
    return ctx.model === undefined ? 0 : 1;
  }

  try {
    // pi 0.78 returns the list synchronously; older/newer hosts may return a promise.
    const available: unknown = await Promise.resolve(modelRegistry.getAvailable());
    return Array.isArray(available) ? available.length : 0;
  } catch {
    return ctx.model === undefined ? 0 : 1;
  }
};

const confirmModelProviderConnection = async (ctx: OutfitterContext): Promise<boolean> => {
  /* v8 ignore next -- pi TUI contexts always provide ui.custom; guards older/reduced hosts. */
  if (!hasContextFunction(ctx.ui, 'custom')) return true;
  const selected = await selectDescribedOption(
    ctx,
    [
      'Pi does not have a model provider connected yet.',
      'Connect one now so Outfitter can use Pi.',
      'Credentials stay inside Pi.',
    ],
    [{ value: 'connect', label: 'Connect a model provider' }],
    'connect',
  );
  return selected === 'connect';
};

const createQuestionUi = (ctx: OutfitterContext): QuestionUi => ({
  async selectSetupMode() {
    const options = [
      'Use the default Outfitter profile catalog',
      'Create your own profile',
      'Provide a different catalog to import',
    ];
    const selected = await ctx.ui.select('How would you like to set up Outfitter?', options);
    if (selected === undefined) return undefined;
    return options.indexOf(selected) === 1 ? 'create' : options.indexOf(selected) === 2 ? 'catalog' : 'default';
  },
  async selectInstallTarget(paths) {
    const items = [
      {
        value: 'home',
        label: 'Home folder (~/.outfitter)',
        description: 'These profiles will be available anywhere you start outfitter.',
      },
      {
        value: 'project',
        label: 'Current project directory (.outfitter)',
        description:
          'These profiles will only be available in the current project directory and will compose the profiles of the same name in the home folder.',
      },
    ];
    const title = ['Where should Outfitter install these settings?'];
    const selected = hasContextFunction(ctx.ui, 'custom')
      ? await selectDescribedOption(ctx, title, items, 'home')
      : await ctx.ui.select(
          title.join('\n'),
          items.map((item) => item.label),
        );
    if (selected === undefined) {
      return undefined;
    }
    const selectedValue = items.some((item) => item.value === selected)
      ? selected
      : items.find((item) => item.label === selected)?.value;
    const target: InstallTarget =
      selectedValue === 'project'
        ? { id: 'project', settingsPath: paths.projectSettingsPath, profilesPath: paths.projectProfilesPath }
        : { id: 'home', settingsPath: paths.homeSettingsPath, profilesPath: paths.homeProfilesPath };
    return target;
  },
  async selectProfile(profiles, currentDefault) {
    const items = profiles.map((profile) => ({
      value: profile.id,
      label: formatProfileLabel(profile, currentDefault),
      description: profile.description,
    }));
    const title = [
      'Outfitter profile setup',
      '',
      "Choose the default profile from the selected catalog for future 'outfitter' launches.",
      'The current Pi process keeps the profile it started with; this setting applies on the next launch.',
    ];
    const initialProfileId =
      currentDefault ?? (profiles.some((profile) => profile.id === 'founder') ? 'founder' : profiles[0]?.id);
    const selectedId = hasContextFunction(ctx.ui, 'custom')
      ? await selectDescribedOption(ctx, title, items, initialProfileId)
      : await ctx.ui.select(
          title.join('\n'),
          items.map((item) => item.label),
        );
    if (selectedId === undefined) {
      return undefined;
    }
    return (
      profiles.find((profile) => profile.id === selectedId) ??
      profiles[items.findIndex((item) => item.label === selectedId)]
    );
  },
  async input(message, defaultValue) {
    if (hasContextFunction(ctx.ui, 'input')) {
      // pi's declared signature takes a placeholder string here; Outfitter has always
      // passed this option object and the flows rely on that call shape, so keep it.
      return ctx.ui.input(message, { defaultValue } as unknown as string);
    }
    const selected = await ctx.ui.select(message + ' [' + defaultValue + ']', [defaultValue]);
    return selected;
  },
  async confirmPrivateCatalog(repository) {
    const privateCatalogOnboarding = await loadPrivateCatalogOnboarding();
    return privateCatalogOnboarding.confirmPrivateCatalog(ctx, selectDescribedOption, repository);
  },
  notify: (message, type = 'info') => {
    ctx.ui.notify(message, type);
  },
});

const loadOnboardingFs = async (): Promise<OnboardingFs> => {
  const [fsModule, pathModule] = await Promise.all([import('node:fs'), import('node:path')]);

  return {
    existsSync: (path) => fsModule.existsSync(path),
    mkdirSync: (path, options) => fsModule.mkdirSync(path, options),
    readFileSync: (path, encoding) => fsModule.readFileSync(path, encoding),
    readdirSync: (path) => fsModule.readdirSync(path),
    statSync: (path) => fsModule.statSync(path),
    writeFileSync: (path, content) => {
      fsModule.writeFileSync(path, content);
    },
    dirname: (path) => pathModule.dirname(path),
    join: (...segments) => pathModule.join(...segments),
  };
};

export const createOutfitterExtension = (config: OutfitterExtensionConfig): ((pi: ExtensionAPI) => void) => {
  return (pi: ExtensionAPI): void => {
    let mode: 'build' | 'plan' = 'build';
    let buildModeTools: string[] | undefined;
    let loginSubmitted = false;

    const updateModeStatus = (ctx: OutfitterContext): void => {
      const color = mode === 'plan' ? 'warning' : 'muted';
      ctx.ui.setStatus('outfitter-mode', ctx.ui.theme.fg(color, 'mode: ' + mode));
    };

    const enterPlanMode = (ctx: OutfitterContext): void => {
      /* v8 ignore next 3 -- plan mode is only entered from build mode; the guard protects future re-entrant callers. */
      if (mode !== 'plan') {
        buildModeTools = pi.getActiveTools();
      }
      mode = 'plan';
      const availableTools = new Set(pi.getAllTools().map((tool) => tool.name));
      const planTools = OUTFITTER_PLAN_TOOLS.filter((toolName) => availableTools.has(toolName));
      pi.setActiveTools(planTools.length > 0 ? planTools : OUTFITTER_PLAN_TOOLS);
      updateModeStatus(ctx);
      ctx.ui.notify('Outfitter mode: plan (read-only tools; Shift+Tab to switch back)', 'info');
    };

    const enterBuildMode = (ctx: OutfitterContext): void => {
      mode = 'build';
      /* v8 ignore next -- build mode is only entered from plan mode, which always saves the active tools. */
      pi.setActiveTools(buildModeTools ?? OUTFITTER_DEFAULT_TOOLS);
      buildModeTools = undefined;
      updateModeStatus(ctx);
      ctx.ui.notify('Outfitter mode: build (normal tools; Shift+Tab for plan mode)', 'info');
    };

    const cycleOutfitterMode = (ctx: OutfitterContext): void => {
      if (mode === 'plan') {
        enterBuildMode(ctx);
        return;
      }

      enterPlanMode(ctx);
    };

    (pi.on as unknown as ProjectTrustRegistrar)('project_trust', (event) => {
      if (!config.autoOpenOutfitter || event.cwd !== config.projectDirectory) {
        return Promise.resolve({ trusted: 'undecided' });
      }

      return Promise.resolve({ trusted: 'yes', remember: true });
    });

    const openLoginIfNoModels = async (ctx: OutfitterContext): Promise<void> => {
      if (loginSubmitted || ctx.mode !== 'tui') return;
      const availableModelCount = await getAvailableModelCount(ctx);
      if (availableModelCount > 0) return;
      if (!(await confirmModelProviderConnection(ctx))) return;
      loginSubmitted = await submitSlashCommand(ctx, '/login');
    };

    const runOutfitterOnboarding = async (ctx: OutfitterContext): Promise<void> => {
      if (!ctx.hasUI) return;
      const fs = await loadOnboardingFs();
      const paths = createOutfitterPaths(config, fs.join);
      const questionUi = createQuestionUi(ctx);

      if (config.setupSourceUri !== undefined) {
        await runProvidedSourceOnboarding(fs, paths, questionUi, config.setupSourceUri);
        await openLoginIfNoModels(ctx);
        return;
      }

      const setupMode = await questionUi.selectSetupMode();

      if (setupMode === undefined) {
        questionUi.notify('Outfitter setup cancelled; no settings were changed.', 'warning');
        await openLoginIfNoModels(ctx);
        return;
      }

      if (setupMode === 'catalog') {
        await runRemoteSettingsOnboarding(fs, paths, questionUi);
        await openLoginIfNoModels(ctx);
        return;
      }

      if (setupMode === 'create') {
        await runCreateProfileOnboarding(fs, paths, questionUi);
        await openLoginIfNoModels(ctx);
        return;
      }

      await runDefaultCatalogOnboarding(config, fs, paths, questionUi);
      await openLoginIfNoModels(ctx);
    };

    pi.registerCommand('outfitter', {
      description: 'Configure Outfitter profile onboarding',
      handler: async (_args, ctx) => {
        await runOutfitterOnboarding(ctx);
      },
    });

    pi.registerCommand('mode', {
      description: 'Toggle Outfitter build/plan mode',
      handler: (_args, ctx) => {
        if (ctx.mode === 'tui') {
          cycleOutfitterMode(ctx);
        }
        return Promise.resolve();
      },
    });

    pi.on('session_start', async (event, ctx) => {
      await exportRuntimeSystemPrompt(ctx);
      if (ctx.mode !== 'tui') return;
      ctx.ui.setHeader((_tui, theme) => {
        const lines = createStartupHeaderLines(config, theme, event.reason === 'startup' && config.autoOpenOutfitter);
        return {
          render: () => lines,
          invalidate: () => undefined,
        };
      });
      updateModeStatus(ctx);
      ctx.ui.onTerminalInput((data) => {
        if (!matchesKey(data, 'shift+tab')) return undefined;
        cycleOutfitterMode(ctx);
        return { consume: true };
      });

      if (event.reason === 'startup' && config.autoOpenOutfitter) {
        await submitSlashCommand(ctx, '/outfitter');
        return;
      }

      await openLoginIfNoModels(ctx);
    });

    pi.on('tool_call', (event) => {
      if (mode !== 'plan' || event.toolName !== 'bash') return Promise.resolve(undefined);

      const command: unknown = (event.input as Readonly<Record<string, unknown>> | undefined)?.command;
      return Promise.resolve({
        block: true,
        reason:
          'Outfitter plan mode blocks Bash commands. Press Shift+Tab to return to build mode. Command: ' +
          (typeof command === 'string' ? command : ''),
      });
    });

    pi.on('context', (event) => {
      const messages = event.messages.filter((message) => !isOutfitterModeContextMessage(message));

      if (mode !== 'plan') {
        return Promise.resolve({ messages });
      }

      const planModeContextMessage = {
        role: 'custom',
        customType: 'outfitter-mode-context',
        content:
          '[OUTFITTER PLAN MODE ACTIVE]\n' +
          'You are in read-only planning mode. Inspect files and explain the implementation plan, but do not modify files, run Bash commands, or claim changes are done. Ask before leaving planning mode.',
        display: false,
      } as AgentMessage;

      return Promise.resolve({
        messages: [...messages, planModeContextMessage],
      });
    });
  };
};
