// Tests run command generated system prompt export behavior.
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, describe, expect, it } from 'vitest';

import { executeRunCommand } from '../../src/cli/commands/RunCommand.js';
import { createProfileSourceCachePath } from '../../src/profiles/ProfileCache.js';

const temporaryRoots: string[] = [];

const createTemporaryRoot = (): string => {
  const root = mkdtempSync(join(tmpdir(), 'outfitter-run-prompt-export-'));
  temporaryRoots.push(root);
  return root;
};

const writeSettings = (homeDirectory: string, content: string): void => {
  mkdirSync(join(homeDirectory, '.outfitter'), { recursive: true });
  writeFileSync(join(homeDirectory, '.outfitter', 'settings.yml'), content);
};

const waitForFileContaining = async (path: string, content: string): Promise<void> => {
  for (let attempt = 0; attempt < 80; attempt += 1) {
    if (existsSync(path) && readFileSync(path, 'utf8').includes(content)) {
      return;
    }

    await new Promise((resolve) => setTimeout(resolve, 50));
  }

  throw new Error(`Timed out waiting for ${path} to contain ${content}.`);
};

const writeProfile = (root: string, id: string, content: string): string => {
  const profileDirectory = join(root, id);
  mkdirSync(profileDirectory, { recursive: true });
  const profilePath = join(profileDirectory, 'profile.yml');
  writeFileSync(profilePath, content);
  return profilePath;
};

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe('run command generated system prompt export', () => {
  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('does not export generated system prompts unless profile_export is enabled', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const profilesDirectory = join(homeDirectory, '.outfitter', 'profiles');
    writeSettings(homeDirectory, 'default_profile: default\nprofile_sources:\n  - path: ./profiles\n');
    writeProfile(
      profilesDirectory,
      'default',
      ['id: default', 'controls:', '  system_prompt: Primary prompt', ''].join('\n'),
    );

    await executeRunCommand(
      { homeDirectory, projectDirectory },
      { writeLine: () => undefined, launcher: { launch: () => Promise.resolve(0) } },
    );

    expect(existsSync(join(profilesDirectory, 'default', 'generated-system-prompt.md'))).toBe(false);
  });

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('exports deterministic Pi system prompts beside directory profiles when profile_export is enabled in settings', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const profilesDirectory = join(homeDirectory, '.outfitter', 'profiles');
    writeSettings(
      homeDirectory,
      'default_profile: default\nprofile_export: true\nprofile_sources:\n  - path: ./profiles\n',
    );
    writeProfile(
      profilesDirectory,
      'default',
      [
        'id: default',
        'controls:',
        '  system_prompt: Primary prompt',
        '  append_system_prompt:',
        '    - First append',
        '    - Second append',
        '',
      ].join('\n'),
    );

    await executeRunCommand(
      { homeDirectory, projectDirectory },
      { writeLine: () => undefined, launcher: { launch: () => Promise.resolve(0) } },
    );

    expect(readFileSync(join(profilesDirectory, 'default', 'generated-system-prompt.md'), 'utf8')).toBe(
      [
        '<!-- Generated by Outfitter before Pi runtime capture. The Pi launch extension overwrites this with ctx.getSystemPrompt(). -->',
        '# Generated Pi prompt fallback',
        '',
        'Profile: default',
        'Prompt source: Pi launch controls',
        '',
        '## system_prompt',
        '',
        'Primary prompt',
        '',
        '## append_system_prompt[0]',
        '',
        'First append',
        '',
        '## append_system_prompt[1]',
        '',
        'Second append',
        '',
      ].join('\n'),
    );
  });

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('exports Pi-effective prompt controls with Pi-specific overrides', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const profilesDirectory = join(homeDirectory, '.outfitter', 'profiles');
    writeSettings(
      homeDirectory,
      'default_profile: default\nprofile_export: true\nprofile_sources:\n  - path: ./profiles\n',
    );
    writeProfile(
      profilesDirectory,
      'default',
      [
        'id: default',
        'controls:',
        '  system_prompt: Generic prompt',
        '  append_system_prompt:',
        '    - Generic append',
        '  pi:',
        '    system_prompt: Pi prompt',
        '    append_system_prompt:',
        '      - Pi append',
        '',
      ].join('\n'),
    );

    await executeRunCommand(
      { homeDirectory, projectDirectory },
      { writeLine: () => undefined, launcher: { launch: () => Promise.resolve(0) } },
    );

    const exported = readFileSync(join(profilesDirectory, 'default', 'generated-system-prompt.md'), 'utf8');
    expect(exported).toContain('Pi prompt');
    expect(exported).toContain('Pi append');
    expect(exported).not.toContain('Generic prompt');
    expect(exported).not.toContain('Generic append');
  });

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-003.8, OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('lets top-level profile_export false disable settings-level generated prompt export', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const profilesDirectory = join(homeDirectory, '.outfitter', 'profiles');
    writeSettings(
      homeDirectory,
      'default_profile: default\nprofile_export: true\nprofile_sources:\n  - path: ./profiles\n',
    );
    writeProfile(
      profilesDirectory,
      'default',
      ['id: default', 'profile_export: false', 'controls:', '  system_prompt: Primary prompt', ''].join('\n'),
    );

    await executeRunCommand(
      { homeDirectory, projectDirectory },
      { writeLine: () => undefined, launcher: { launch: () => Promise.resolve(0) } },
    );

    expect(existsSync(join(profilesDirectory, 'default', 'generated-system-prompt.md'))).toBe(false);
  });

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-003.8, OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('exports generated Pi system prompts beside flat profiles without an agent filename suffix', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const profilesDirectory = join(homeDirectory, '.outfitter', 'profiles');
    mkdirSync(profilesDirectory, { recursive: true });
    writeSettings(homeDirectory, 'default_profile: a..b\nprofile_sources:\n  - path: ./profiles\n');
    writeFileSync(
      join(profilesDirectory, 'a..b.yml'),
      ['profile_export: true', 'controls:', '  system_prompt: Flat prompt', ''].join('\n'),
    );

    await executeRunCommand(
      { homeDirectory, projectDirectory },
      { writeLine: () => undefined, launcher: { launch: () => Promise.resolve(0) } },
    );

    expect(readFileSync(join(profilesDirectory, 'a..b.generated-system-prompt.md'), 'utf8')).toContain('Flat prompt');
  });

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('does not change launch args, launch env, or composite profile contents when export is enabled', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const profilesDirectory = join(homeDirectory, '.outfitter', 'profiles');
    writeSettings(
      homeDirectory,
      'default_profile: default\nprofile_export: true\nprofile_sources:\n  - path: ./profiles\n',
    );
    writeProfile(
      profilesDirectory,
      'default',
      [
        'id: default',
        'state_persistence:',
        '  settings.json: warn',
        'controls:',
        '  model: test-model',
        '  environment:',
        '    EXPORT_TEST: yes',
        '  system_prompt: Primary prompt',
        '',
      ].join('\n'),
    );
    const warnings: string[] = [];

    const result = await executeRunCommand(
      { homeDirectory, projectDirectory, passThroughArgs: ['prompt text'] },
      {
        writeError: (message) => warnings.push(message),
        writeLine: () => undefined,
        launcher: {
          launch(plan) {
            writeFileSync(join(plan.env.PI_CODING_AGENT_DIR, 'settings.json'), '{"export":"state"}\n');
            return Promise.resolve(0);
          },
        },
      },
    );

    expect(result.launchPlan.args).toContain('--model');
    expect(result.launchPlan.args).toContain('test-model');
    expect(result.launchPlan.args.at(-1)).toBe('prompt text');
    expect(result.launchPlan.env.EXPORT_TEST).toBe('yes');
    expect(result.launchPlan.env.OUTFITTER_SYSTEM_PROMPT_EXPORT_PATH).toBe(
      join(profilesDirectory, 'default', 'generated-system-prompt.md'),
    );
    expect(readFileSync(join(result.compositeProfileDirectory, 'outfitter', 'profile.json'), 'utf8')).toContain(
      'test-model',
    );
    expect(result.warnings).toContain(
      "pi wrote 'settings.json' with state_persistence 'warn' and it was not persisted.",
    );
    expect(warnings).toEqual(result.warnings);
  });

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('refreshes generated prompt exports when watched profile inputs change', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const profilesDirectory = join(homeDirectory, '.outfitter', 'profiles');
    writeSettings(
      homeDirectory,
      'default_profile: default\nprofile_export: true\nprofile_sources:\n  - path: ./profiles\n',
    );
    const profilePath = writeProfile(
      profilesDirectory,
      'default',
      ['id: default', 'controls:', '  system_prompt: Initial prompt', ''].join('\n'),
    );
    const exportPath = join(profilesDirectory, 'default', 'generated-system-prompt.md');

    await executeRunCommand(
      { homeDirectory, projectDirectory },
      {
        writeLine: () => undefined,
        launcher: {
          async launch() {
            await new Promise((resolve) => setTimeout(resolve, 50));
            writeFileSync(
              profilePath,
              ['id: default', 'controls:', '  system_prompt: Refreshed prompt', ''].join('\n'),
            );
            await waitForFileContaining(exportPath, 'Refreshed prompt');
            return 0;
          },
        },
      },
    );

    expect(readFileSync(exportPath, 'utf8')).toContain('Refreshed prompt');
  }, 10000);

  // THIS TEST VALIDATES A HARD REQUIREMENT (OFTR-005.7).
  // YOU MUST NOT MODIFY THIS TEST UNLESS THE REQUIREMENT CHANGES.
  it('skips generated prompt export for cache-backed profile owners with an actionable warning', async () => {
    const root = createTemporaryRoot();
    const homeDirectory = join(root, 'home');
    const projectDirectory = join(root, 'project');
    const uri = 'git+https://example.test/profiles.git';
    const cacheDirectory = createProfileSourceCachePath(homeDirectory, uri);
    writeSettings(homeDirectory, `default_profile: cached\nprofile_export: true\nprofile_sources:\n  - uri: ${uri}\n`);
    writeProfile(
      cacheDirectory,
      'cached',
      ['id: cached', 'controls:', '  system_prompt: Cached prompt', ''].join('\n'),
    );
    const warnings: string[] = [];

    await executeRunCommand(
      { homeDirectory, projectDirectory },
      {
        writeError: (message) => warnings.push(message),
        writeLine: () => undefined,
        launcher: { launch: () => Promise.resolve(0) },
      },
    );

    expect(existsSync(join(cacheDirectory, 'cached', 'generated-system-prompt.md'))).toBe(false);
    expect(warnings.join('\n')).toContain("System prompt export skipped for profile 'cached'");
  });
});
