// Copies docs/documentation/*.md into the Nextra app as generated pages so the
// repository documentation stays the single content source for the doc site.
//
// - Source of truth: <repo>/docs/documentation/**/*.md
// - Output: <doc_site>/app/docs/**/page.md plus generated _meta.js nav files
// - Nav order mirrors the index lists in docs/documentation/README.md
//
// The output directory is fully regenerated on every run (predev/prebuild) and
// is gitignored; never edit files under app/docs by hand.
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, posix, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const docSiteRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repositoryRoot = resolve(docSiteRoot, '..', '..');
const documentationRoot = join(repositoryRoot, 'docs', 'documentation');
const outputRoot = join(docSiteRoot, 'app', 'docs');
const repositoryBlobBase = 'https://github.com/ai-outfitter/outfitter/blob/main';

/** Lists every markdown file under docs/documentation as a posix-relative path. */
const listMarkdownFiles = (directory, prefix = '') => {
  const entries = readdirSync(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const relativePath = prefix === '' ? entry.name : `${prefix}/${entry.name}`;

    if (entry.isDirectory()) {
      files.push(...listMarkdownFiles(join(directory, entry.name), relativePath));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      files.push(relativePath);
    }
  }

  return files.sort();
};

/** Converts a documentation-relative source path to a site route, e.g. usecases/engineering.md -> /docs/usecases/engineering. */
const routeForSource = (sourcePath) => {
  if (sourcePath === 'README.md') {
    return '/docs';
  }

  return `/docs/${sourcePath.replace(/\.md$/, '')}`;
};

/** Rewrites one markdown link target found in a file at sourcePath. */
const rewriteLinkTarget = (target, sourcePath) => {
  if (/^[a-z][a-z0-9+.-]*:/i.test(target) || target.startsWith('#') || target.startsWith('/')) {
    return target;
  }

  const [pathPart, fragment = ''] = target.split('#', 2);

  if (!pathPart.endsWith('.md')) {
    return target;
  }

  const sourceDirectory = posix.dirname(sourcePath);
  const resolved = posix.normalize(posix.join(sourceDirectory === '.' ? '' : sourceDirectory, pathPart));
  const fragmentSuffix = fragment === '' ? '' : `#${fragment}`;

  if (!resolved.startsWith('..')) {
    return `${routeForSource(resolved)}${fragmentSuffix}`;
  }

  // Links that escape docs/documentation (for example ../philosophy.md) point at
  // repository files the site does not render; send them to GitHub instead.
  const repositoryPath = posix.normalize(posix.join('docs/documentation', sourceDirectory, pathPart));
  return `${repositoryBlobBase}/${repositoryPath}${fragmentSuffix}`;
};

/** Rewrites inline markdown links so cross-doc references resolve as site routes. */
const rewriteLinks = (markdown, sourcePath) =>
  markdown.replace(/\]\(([^()\s]+)\)/g, (match, target) => `](${rewriteLinkTarget(target, sourcePath)})`);

/** Reads the nav order and titles from the README index lists. */
const parseReadmeIndex = (readmeMarkdown) => {
  const entries = [];
  const linkPattern = /^-\s+\[([^\]]+)\]\(\.\/([^)#\s]+\.md)\)/;

  for (const line of readmeMarkdown.split('\n')) {
    const match = linkPattern.exec(line.trim());

    if (match !== null) {
      entries.push({ title: match[1], sourcePath: posix.normalize(match[2]) });
    }
  }

  return entries;
};

const readFirstHeading = (markdown) => {
  const match = /^#\s+(.+)$/m.exec(markdown);
  return match === null ? undefined : match[1].trim();
};

const writeGeneratedMeta = (filePath, entries) => {
  const body = entries
    .map(({ key, title }) => `  ${JSON.stringify(key)}: { title: ${JSON.stringify(title)} },`)
    .join('\n');
  writeFileSync(filePath, `// Generated by scripts/sync-docs.mjs. Do not edit.\nexport default {\n${body}\n};\n`);
};

const sourceFiles = listMarkdownFiles(documentationRoot);
rmSync(outputRoot, { recursive: true, force: true });
mkdirSync(outputRoot, { recursive: true });

const titlesBySource = new Map();

for (const sourcePath of sourceFiles) {
  const markdown = readFileSync(join(documentationRoot, sourcePath), 'utf8');
  const outputPath =
    sourcePath === 'README.md'
      ? join(outputRoot, 'page.md')
      : join(outputRoot, sourcePath.replace(/\.md$/, ''), 'page.md');

  titlesBySource.set(sourcePath, readFirstHeading(markdown) ?? posix.basename(sourcePath, '.md'));
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, rewriteLinks(markdown, sourcePath));
}

const indexEntries = parseReadmeIndex(readFileSync(join(documentationRoot, 'README.md'), 'utf8')).filter((entry) =>
  titlesBySource.has(entry.sourcePath),
);
const indexedSources = new Set(indexEntries.map((entry) => entry.sourcePath));
const unindexedSources = sourceFiles.filter(
  (sourcePath) => sourcePath !== 'README.md' && !indexedSources.has(sourcePath),
);

const topLevelMeta = [{ key: 'index', title: 'Overview' }];
const usecasesMeta = [];

for (const entry of [
  ...indexEntries,
  ...unindexedSources.map((sourcePath) => ({ title: titlesBySource.get(sourcePath), sourcePath })),
]) {
  const key = posix.basename(entry.sourcePath, '.md');

  if (posix.dirname(entry.sourcePath) === 'usecases') {
    usecasesMeta.push({ key, title: entry.title });
  } else {
    topLevelMeta.push({ key, title: entry.title });
  }
}

if (usecasesMeta.length > 0) {
  topLevelMeta.push({ key: 'usecases', title: 'Use cases' });
  writeGeneratedMeta(join(outputRoot, 'usecases', '_meta.js'), usecasesMeta);
}

writeGeneratedMeta(join(outputRoot, '_meta.js'), topLevelMeta);
process.stdout.write(`sync-docs: generated ${sourceFiles.length} pages from docs/documentation into app/docs\n`);
