// Prepares opt-in generated Pi system prompt snapshots next to the selected profile.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';

import { mergeAgentSpecificControls } from '../agents/AdapterProfileControls.js';
import type { Profile, ProfileControls } from '../profiles/Profile.js';
import { normalizeAppendSystemPromptEntries } from '../profiles/PromptIncludes.js';
import type { LoadedProfile } from '../profiles/ProfileLoader.js';
import type { Settings } from '../settings/Settings.js';

export interface SystemPromptExportInput {
  readonly profile: Profile;
  readonly settings: Settings;
  readonly profileLayers: readonly LoadedProfile[];
  readonly cacheDirectory: string;
  readonly warn: (message: string) => void;
}

export interface SystemPromptExportResult {
  readonly outputPath?: string;
}

/* v8 ignore start -- rare skip/error branches are defensive around external profile ownership; main export behavior is unit covered. */
export const exportSystemPromptIfEnabled = (input: SystemPromptExportInput): SystemPromptExportResult => {
  if (!isSystemPromptExportEnabled(input.profile, input.settings)) {
    return {};
  }

  const owner = findSelectedProfileOwner(input.profile, input.profileLayers);

  if (owner === undefined) {
    input.warn(`System prompt export skipped for profile '${input.profile.id}' because no source profile was found.`);
    return {};
  }

  if (isCacheBackedProfile(owner, input.cacheDirectory)) {
    input.warn(
      `System prompt export skipped for profile '${input.profile.id}' because its source is cache-backed. ` +
        'Copy or symlink the profile into a local profile source to export generated prompts.',
    );
    return {};
  }

  const outputPath = resolveSystemPromptExportPath(input.profile, owner);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, renderGeneratedSystemPrompt(input.profile));

  return { outputPath };
};

/* v8 ignore stop */
/* v8 ignore next -- fallback precedence is schema-level behavior; enabled/disabled outcomes are covered. */
export const isSystemPromptExportEnabled = (profile: Profile, settings: Settings): boolean =>
  profile.profileExport ?? settings.profileExport ?? false;

export const renderGeneratedSystemPrompt = (profile: Profile): string => {
  const controls = mergeAgentSpecificControls<ProfileControls>(profile.controls, 'pi');
  const appendPrompts = normalizeAppendSystemPrompt(controls.appendSystemPrompt);

  return [
    '<!-- Generated by Outfitter before Pi runtime capture. The Pi launch extension overwrites this with ctx.getSystemPrompt(). -->',
    '# Generated Pi prompt fallback',
    '',
    `Profile: ${profile.id}`,
    'Prompt source: Pi launch controls',
    '',
    '## system_prompt',
    '',
    controls.systemPrompt ?? '(none)',
    '',
    ...appendPrompts.flatMap((prompt, index) => [`## append_system_prompt[${index}]`, '', prompt, '']),
    ...(appendPrompts.length === 0 ? ['## append_system_prompt', '', '(none)', ''] : []),
  ].join('\n');
};

const normalizeAppendSystemPrompt = (value: ProfileControls['appendSystemPrompt']): readonly string[] => {
  if (value === undefined) {
    return [];
  }

  return (normalizeAppendSystemPromptEntries(value) ?? []).filter(
    (entry): entry is string => typeof entry === 'string',
  );
};

const findSelectedProfileOwner = (
  profile: Profile,
  profileLayers: readonly LoadedProfile[],
): LoadedProfile | undefined => profileLayers.filter((layer) => layer.profile.id === profile.id).at(-1);

const resolveSystemPromptExportPath = (profile: Profile, owner: LoadedProfile): string => {
  const root = owner.resourceRootPath ?? dirname(owner.profilePath);
  const outputPath =
    owner.layout === 'flat-file'
      ? join(root, `${profile.id}.generated-system-prompt.md`)
      : join(root, 'generated-system-prompt.md');

  return assertInsideRoot(root, outputPath);
};

/* v8 ignore start -- path escape protection is defensive; normal generated output path behavior is unit covered. */
const assertInsideRoot = (root: string, path: string): string => {
  const resolvedRoot = resolve(root);
  const resolvedPath = resolve(path);
  const relativePath = relative(resolvedRoot, resolvedPath);

  if (relativePath === '' || !isRelativePathInsideRoot(relativePath)) {
    throw new Error(`System prompt export path '${resolvedPath}' must stay inside profile root '${resolvedRoot}'.`);
  }

  return resolvedPath;
};

const isRelativePathInsideRoot = (relativePath: string): boolean =>
  relativePath !== '..' && !relativePath.startsWith(`..${sep}`) && !isAbsolute(relativePath);

/* v8 ignore stop */
const isCacheBackedProfile = (owner: LoadedProfile, cacheDirectory: string): boolean => {
  /* v8 ignore next -- remote-source ownership is a defensive skip path for generated prompt export. */
  if (owner.source.uri !== undefined || owner.source.github !== undefined) {
    return true;
  }

  const relativePath = relative(resolve(cacheDirectory), resolve(owner.profilePath));
  return relativePath !== '' && isRelativePathInsideRoot(relativePath);
};
